spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bookdb
  flyway:
    enabled: false
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379
    connect-timeout: 10000
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: library
      time-to-live: 60000
